# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: true
    enp2s0:
      addresses:
        - 10.20.117.2/24
      nameservers:
        addresses:
          - 127.0.0.1
  version: 2
